sonar.projectKey=ammaz-mern-10pshine
sonar.projectName=Ammaz MERN 10pshine
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=squ_9e0318f69a64fc6aaf37b1fb933dbac313d96e64